version: "3.8"
services:
  agents-handler:
    build:
      context: ./agents-handler
      dockerfile: Dockerfile
    container_name: agents-handler
    restart: unless-stopped
    ports:
      - "8070:8070"
    environment:
      - OPENAI_API_KEY=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
      - MONGODB_URI=mongodb://mongo:27017
      - MONGO_DB=brand-hero
      - PORT=8070
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=brand_hero
    depends_on:
      - mongo
      - qdrant
    networks:
      - agents-network
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: agents_handler
    volumes:
      - mongo_data:/data/db
    networks:
      - agents-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  # API i GRPC
      - "6334:6334"  # Dashboard
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
      - QDRANT_TELEMETRY_DISABLED=true
    networks:
      - agents-network

networks:
  agents-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  qdrant_data:
    driver: local
