

spring:
  ai:
#    vectorstore:
#      qdrant:
#        url: http://localhost:6333
#        collection-name: brand_hero
#        initialize-schema: true
    openai:
      api-key: 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

  data:
    mongodb:
      host: localhost
      port: 27017
      database: brand-hero

facebook:
  api:
    version: v18.0
    base-url: https://graph.facebook.com/

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.brandhero: DEBUG

agent:
  endpoint:
    url: http://localhost:5000/api/agent
  post:
    limit: 1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /v3/api-docs/swagger-ui.html
server:
  port: 8090
