package com.brandhero.model;

import java.time.LocalDateTime;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a company context generated by the agent based on Facebook page data.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "company_contexts")
public class CompanyContext {
    
    @Id
    private String id;
    
    private String pageId;
    private String pageName;
    
    private String userId;
    private String username;
    
    private String contextContent;
    
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();
    
    private LocalDateTime updatedAt;
    
    // Store the posts that were used to generate this context
    private List<String> postIds;
    
    // Number of posts used to generate this context
    private Integer postsCount;
    
    /**
     * Updates the context with new content.
     * 
     * @param newContent the new context content
     */
    public void updateContext(String newContent) {
        this.contextContent = newContent;
        this.updatedAt = LocalDateTime.now();
    }
}
